### ISSUE TITLE
How can i download chinese or janpanese srts?

### ISSUE THREAD

**Issue by xiaosongfu** [ssamadgh/WWDCsrt#2]
thanks for your reply.

**Comment by owenzhao** [comment]
You need to clone this project first.

Then in Xcode search "subtitles/eng/". 

For Chinese subtitles, replacing the searched result's "eng" to "zho".

For Japanese, replacing "eng" to "jpn".

Then you run the app again in Xcode. It will download the specified language subtitles automatically.
