### ISSUE TITLE
Frequently got "Error: No valid video link is imported".

### ISSUE THREAD

**Issue by owenzhao** [ssamadgh/WWDCsrt#3]
<img width="663" alt="2019_issue" src="https://user-images.githubusercontent.com/2182896/81160991-70116300-8fbd-11ea-8b03-0fd61e490611.png">

This issue may have relation with the other issue that I reported.

**Comment by ssamadgh** [comment]
Hi @owenzhao  this issue is now fixed, Thanks for your report!
