### ISSUE TITLE
Downloading "all sessions" only downloads previously downloaded subtitles.

### ISSUE THREAD

**Issue by owenzhao** [ssamadgh/WWDCsrt#4]
Steps:

1. Download one session, say 2019 720.
2. Choose download "All Sessions".
3. "All Sessions" only downloads the 2019 720 and stops.

Maybe when downloaded the single session, all sessions list was over-written. The evidence is that when I used the app for the very first time in a virtual machine with no single session downloaded before, downloading with "all sessions" worked.

**Comment by ssamadgh** [comment]
Hi, thanks for your issues, I'll check them as soon as possible.
Regards,

**Comment by ssamadgh** [comment]
Hi @owenzhao this issue is now fixed. Thanks for your report!
